export const FORM_XS_DEFAULT_GRID_SIZE = 12;
export const FORM_SM_DEFAULT_GRID_SIZE = 6;
export const FORM_MD_DEFAULT_GRID_SIZE = 4;
export const FORM_LG_DEFAULT_GRID_SIZE = 3;
export const FORM_XL_DEFAULT_GRID_SIZE = 3;
